apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "jenkins.192.168.0.19.nip.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-service
          servicePort: 80
  - host: "gitea.192.168.0.19.nip.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 80
  - host: "*.app.192.168.0.19.nip.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: genexposer-service
          servicePort: 80
