apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "*.inf.127.0.0.1.nip.io"
    http:
      paths:
      - path: /jenkins
        backend:
          serviceName: jenkins-service
          servicePort: 80
      - path: /nginx
        backend:
          serviceName: nginx-pr123-public
          servicePort: 80
  - host: "*.app.127.0.0.1.nip.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: genexposer-service
          servicePort: 80
